- resources/js/components/batch/forms/BatchMintForm.vue
- resources/js/components/batch/forms/BatchTransferForm.vue
- resources/js/components/beam/ClaimableTokenForm.vue
- resources/js/components/fueltank/DispatchRuleForm.vue
- resources/js/components/pages/Tokens.vue
- resources/js/util/index.ts
- Fixed in beam create page with a validation issue where user input number and its changed to string
> fix form validations

- resources/js/api/auth.ts
- resources/js/api/mutations.ts
- resources/js/components/pages/Settings.vue
- resources/js/graphql/mutation/auth/DeleteAccount.ts
enhancement
___
- Added functionality to delete a user account from the settings page for non-multi-tenant users.
- Introduced a confirmation modal to confirm account deletion.
- Implemented the backend API method for account deletion.
- Defined the GraphQL mutation required for the delete account functionality.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Add Delete Account Functionality and Confirmation Modal</code>&nbsp; &nbsp; </dd></summary>
<hr>
<li>Added a button to delete account for non-multi-tenant users.<br> <li> Introduced a confirmation modal for account deletion.<br> <li> …
> [PLA-1634] add delete account

- resources/js/components/pages/Settings.vue
bug_fix
___
- Fixed the condition to correctly display the "Delete account" button for users in a multi-tenant environment. Previously, the button was hidden for multi-tenant users, but with this update, it will be correctly shown.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Fix Condition for Showing Delete Account Button in Multi-Tenant </code><br><code>Environment</code></dd></summary>
<hr>
<li>Adjusted the condition to show the "Delete account" button for <br>multi-tenant users.<br>
</details>
</td>
<td><a href="https:/enjin/platform-ui/pull/82/files#diff-9408c437ed722b0b729de4bd17db6e7 …
> [PLA-1634] show delete button for multi tenant

- resources/js/components/pages/FuelTanks.vue
- resources/js/components/slideovers/fueltank/FreezeFuelTankSlideover.vue
___
- Updated the action name in the Fuel Tanks page to 'Freeze / Unfreeze' for better user understanding.
- Made `ruleSetId` field optional in the Freeze Fuel Tank form to allow more flexibility in fuel tank management.
___
<tr>
<td>
<details>
<summary><strong>FuelTanks.vue</strong><dd><code>Update Action Name for Clarity in Fuel Tanks Page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/FuelTanks.vue
<li>Updated the action name from 'Schedule Freeze' to 'Freeze / Unfreeze' <br>for clarity.<br>
</details>
</td>
<td><a …
> [PLA-1650] fix fuel tank freeze

- resources/js/components/CollapseCard.vue
- resources/js/components/CopyTextIcon.vue
- resources/js/components/pages/SettingsApiTokens.vue
___
- Enhanced the user experience in the `CollapseCard` component by making the entire card header clickable and increasing the content area.
- Refactored `CopyTextIcon` for better flexibility and alignment, allowing custom content to be inserted alongside the icon.
- Improved the display and management of API tokens in the settings page, including a more graceful handling of tokens and a better visual representation.
___
<tr>
<td>
<details>
<summary><strong>CollapseCard.vue</strong><dd><code>Enhance CollapseCard UX and Viewability</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> [PLA-1671] fix settings api token copy

- resources/js/api/index.ts
- resources/js/api/mutations.ts
- resources/js/components/FormInput.vue
- resources/js/components/pages/Wallets.vue
- resources/js/components/slideovers/common/TransferBalanceSlideover.vue
- resources/js/graphql/mutation/TransferBalance.ts
enhancement
___
- Introduced a new "Transfer Balance" feature across various components and services.
- Enhanced the `FormInput` component to disable autocomplete and improve numeric input handling.
- Reworked the Wallet page layout to include a "Transfer Balance" button, integrating it with a new slide-over component.
- Implemented the backend logic for the balance transfer feature, including API service method, GraphQL mutation, and form submission handling.
___
<tr>
<td>
<details>
<summary><strong>FormInput.vue</strong><dd><code>Enhancements to FormInput Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> [PLA-1677] transfer balance feature

- resources/js/components/pages/Settings.vue
- resources/js/components/pages/SettingsApiTokens.vue
- resources/js/components/pages/auth/Login.vue
- resources/js/util/index.ts
bug_fix, enhancement
___
- Centered the settings page content for better user experience.
- Improved the UI in the API Tokens section by adjusting the background color and layout.
- Fixed the condition to display the resend verification email option on the login page.
- Enhanced error handling during login to better manage unverified email errors.
- Simplified error handling in the `snackbarErrors` function.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Center Alignment of Settings Page Content</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> [PLA-1543] fix email resend

- resources/js/components/pages/auth/ResetPassword.vue
- resources/js/store/index.ts
bug_fix, enhancement
___
This PR introduces several improvements and bug fixes related to error handling and multi-tenant functionality:
- Enhanced error handling in the password reset process to provide specific feedback for too many requests and other errors.
- Fixed the multi-tenant check in the app store to correctly identify tenant configurations and adjust the login process accordingly.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ResetPassword.vue</strong><dd><code>Enhanced Password Reset Error Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> [PLA-1702] handle error throttle

- resources/js/components/fueltank/DispatchRuleForm.vue
- resources/js/store/transaction.ts
enhancement
___
- Improved code formatting in `DispatchRuleForm.vue` for better readability.
- Enhanced type safety in `transaction.ts` by using `HexString` type for the `era` field.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting
<tr>
<td>
<details>
<summary><strong>DispatchRuleForm.vue</strong><dd><code>Improve readability of FormInput component in Vue file</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/fueltank/DispatchRuleForm.vue
- Reformatted the `FormInput` component for better readability.
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/93/files#diff-cc58d96b1ce3f55625c0d859e23b6695326b1339253a7da7d8c4fd8a2a6d39fc">+8/-1</a>&nbsp; &nbsp; …
> hotfix: ts-fix

- resources/js/api/auth.ts
- resources/js/components/pages/auth/Login.vue
- resources/js/components/pages/auth/Register.vue
- resources/js/components/pages/auth/RequestResetPassword.vue
- resources/js/graphql/mutation/auth/RegisterUser.ts
- resources/js/graphql/mutation/auth/RequestPasswordReset.ts
- resources/js/graphql/query/auth/Login.ts
- resources/js/store/index.ts
- resources/views/app.blade.php
___
- Updated the captcha integration in both Login and Register Vue components to handle cases where the captcha key might not be set, avoiding unnecessary captcha interactions.
- Fixed typos in method names related to captcha verification, enhancing code reliability.
- Improved the global configuration script in `app.blade.php` to use Laravel's `config` function, ensuring better performance and reliability.
___
<tr>
<td>
<details>
<summary><strong>Login.vue</strong><dd><code>Enhance and Fix Captcha Integration in Login Component</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/auth/Login.vue
<li>Fixed …
> [PLA-1727] Update recaptcha logic

- resources/js/components/pages/auth/Login.vue
- resources/js/components/pages/auth/Register.vue
- resources/js/components/pages/auth/RequestResetPassword.vue
bug_fix, enhancement
___
- Added conditions to disable form submission buttons ('Sign in', 'Register', 'Reset Password') in various authentication-related components until the captcha badge is visible.
- Modified captcha script loading logic to ensure the captcha badge visibility state is set appropriately, enhancing security measures across login, registration, and password reset functionalities.
___
<tr>
<td>
<details>
<summary><strong>Login.vue</strong><dd><code>Enhance Login Security with Captcha Visibility Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/auth/Login.vue
<li>Added a condition to disable …
> [PLA-1736] fix recaptcha loading

- resources/js/api/auth.ts
- resources/js/api/mutations.ts
- resources/js/api/queries.ts
- resources/js/graphql/mutation/auth/RegisterUser.ts
- resources/js/graphql/mutation/auth/RegisterUserRecaptcha.ts
- resources/js/graphql/mutation/auth/RequestPasswordResetRecaptcha.ts
- resources/js/graphql/query/auth/Login.ts
- resources/js/graphql/query/auth/LoginRecaptcha.ts
enhancement
___
- Added conditional logic in `AuthApi` methods to select queries and mutations based on reCAPTCHA presence.
- Introduced new GraphQL queries and mutations for handling authentication with reCAPTCHA.
- Simplified existing queries and mutations by removing reCAPTCHA parameters where separate reCAPTCHA versions were created.
___
<tr>
<td>
<details>
<summary><strong>auth.ts</strong><dd><code>Integrate optional reCAPTCHA in authentication methods</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/api/auth.ts
<li>Added conditional logic to use different GraphQL queries and mutations <br>based on the presence of a …
> [PLA-1728] add optional recaptcha

- resources/js/components/CollapseCard.vue
- resources/js/components/NotificationsList.vue
- resources/js/components/ProfileMenu.vue
- resources/js/components/batch/BatchMint.vue
- resources/js/components/fueltank/DispatchRuleForm.vue
- resources/js/components/pages/Collections.vue
- resources/js/components/pages/Settings.vue
- resources/js/components/pages/SettingsResetPassword.vue
- resources/js/components/pages/Tokens.vue
- resources/js/components/pages/create/CreateCollection.vue
- resources/js/components/pages/create/CreateToken.vue
- resources/js/store/transaction.ts
Enhancement
___
- Added `dusk` and `dusk-id` attributes across various components to improve testability and ensure elements are easily selectable in tests.
- Enhanced the reset password form by adding specific IDs to form elements, aiding in both form management and automated testing.
- Minor cleanup in the captcha logic for the registration process.
___
<tr>
<td>
<details>
<summary><strong>CollapseCard.vue</strong><dd><code>Add Dusk ID Prop for Testing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> [PLA-1417] Add dusk id

- resources/js/api/beam.ts
- resources/js/api/index.ts
- resources/js/api/queries.ts
- resources/js/api/transaction.ts
- resources/js/components/beam/BeamsList.vue
- resources/js/components/beam/ClaimsList.vue
- resources/js/components/marketplace/BidsList.vue
- resources/js/components/marketplace/ListingsList.vue
- resources/js/components/marketplace/SalesList.vue
- resources/js/components/pages/Collections.vue
- resources/js/components/pages/FuelTanks.vue
- resources/js/components/pages/Tokens.vue
- resources/js/components/pages/Transactions.vue
- resources/js/components/pages/Wallets.vue
- resources/js/components/pages/auth/Login.vue
- resources/js/components/pages/create/CreateBeam.vue
- resources/js/factory/wallet.ts
- resources/js/graphql/query/GetWallets.ts
- resources/js/graphql/query/beam/GetBeam.ts
- resources/js/graphql/query/beam/GetBeams.ts
- resources/js/graphql/query/beam/GetSingleUseCodes.ts
- resources/js/store/index.ts
- resources/js/types/types.interface.ts
___
- Added `useAppStore` import and initialization across multiple components.
- Introduced `isInternal` computed property and updated API calls to include `internal` parameter.
- Ensured `appStore.initPromise` is awaited on component mount for various components.
- Implemented wallet fetching and pagination in Wallets component.
- Added `getWallets` method to Transaction API and `GetWallets` GraphQL query.
- Modified `init` method in app store to set and await `initPromise`.
- Handled empty wallet data in `DTOWalletFactory`.
___
</strong></td><td><details><summary>20 files</summary><table>
<tr>
<td>
<details> …
> [PLA-1773] fix wallet and beam query

- resources/js/components/ConfirmModal.vue
- resources/js/components/FormDateInput.vue
- resources/js/components/FormSelect.vue
- resources/js/components/beam/BeamsList.vue
- resources/js/components/beam/ClaimsList.vue
- resources/js/components/fueltank/DispatchRuleForm.vue
- resources/js/components/marketplace/BidsList.vue
- resources/js/components/marketplace/ListingsList.vue
- resources/js/components/marketplace/SalesList.vue
- resources/js/components/pages/FuelTanks.vue
- resources/js/components/pages/Transactions.vue
- resources/js/components/pages/Wallets.vue
- resources/js/components/pages/create/CreateBeam.vue
- resources/js/components/pages/create/CreateFuelTank.vue
- resources/js/components/slideovers/beam/ClaimBeamSlideover.vue
- resources/js/components/slideovers/common/RetryTransactionSlideover.vue
Enhancement
___
- Added `dusk` attributes to various buttons and elements across multiple Vue.js components to improve testability.
- Added `name` attributes to input fields in `FormDateInput` and `FormSelect` components.
- Added `id` attributes to tables in several components for better identification.
___
</strong></td><td><details><summary>16 files</summary><table>
<tr>
<td>
<details>
<summary><strong>ConfirmModal.vue</strong><dd><code>Add dusk IDs to ConfirmModal buttons</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> [PLA-1417] Add element dusk id

- resources/js/components/pages/create/CreateBeam.vue
- resources/js/components/pages/create/CreateFuelTank.vue
___
- Fixed spacing issue in `duskId` attribute in `CreateBeam.vue`.
- Updated CSS classes for better color contrast in `CreateBeam.vue`.
- Added a new `MultiCheckbox` for deposit options in `CreateFuelTank.vue`.
- Updated labels and options for fuel tank flags in `CreateFuelTank.vue`.
- Improved color contrast in CSS classes in `CreateFuelTank.vue`.
- Added `watch` function to handle flag dependencies in `CreateFuelTank.vue`.
___
<tr>
<td>
<details>
<summary><strong>CreateBeam.vue</strong><dd><code>Fix spacing and improve color contrast in CreateBeam component.</code></dd></summary>
<hr> …
> [PLA-1793] fix fueltank creation options

- resources/js/api/index.ts
- resources/js/components/UserNavbar.vue
- resources/js/components/pages/SettingsWalletAccount.vue
- resources/js/components/pages/auth/Login.vue
- resources/js/components/pages/auth/Register.vue
- resources/js/components/slideovers/common/TransferBalanceSlideover.vue
- resources/js/graphql/mutation/TransferBalance.ts
___
- Added text color classes for light and dark themes in various components.
- Updated wallet daemon documentation URL.
- Added `signingAccount` field to the transfer balance form and included it in the API call and GraphQL mutation.
___
<tr>
<td>
<details>
<summary><strong>UserNavbar.vue</strong><dd><code>Add text color classes to UserNavbar component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/UserNavbar.vue
<li>Added text color classes to <code>span</code> elements for light and dark themes.<br>
</details>
</td>
<td><a …
> [PLA-1677] balance transfer

- resources/js/api/beam.ts
- resources/js/api/queries.ts
- resources/js/components/beam/BeamsList.vue
- resources/js/graphql/query/beam/GetBeamInternal.ts
- resources/js/graphql/query/beam/GetBeamsInternal.ts
- resources/js/graphql/query/beam/GetSingleUseCodesInternal.ts
___
- Added new internal queries for beams and single-use codes with `claimConditions`.
- Removed `internal` parameter from existing queries and adjusted logic accordingly.
- Refactored button elements in `BeamsList.vue` for better readability.
___
</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>BeamsList.vue</strong><dd><code>Refactor button elements for readability.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/beam/BeamsList.vue
- Reformatted button elements for better readability.
</details> …
> [PLA-1783] add internal beams query

- resources/js/components/batch/forms/BatchMintForm.vue
- resources/js/components/batch/forms/BatchTransferForm.vue
- resources/js/components/pages/create/CreateToken.vue
- resources/js/util/index.ts
___
- Added `validateToken` function to validate different token ID types in `resources/js/util/index.ts`.
- Integrated token ID validation in `BatchMintForm.vue`, `BatchTransferForm.vue`, and `CreateToken.vue`.
- Display error messages using `snackbar` if token ID is invalid in the respective components.
___
<tr>
<td>
<details>
<summary><strong>BatchMintForm.vue</strong><dd><code>Add token ID validation and error handling.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/batch/forms/BatchMintForm.vue
<li>Added <code>validateToken</code> …
> [PLA-1856] token create validation

- package-lock.json
- package.json
- resources/js/components/MultiCheckbox.vue
- resources/js/components/Popover.vue
- resources/js/components/Toggle.vue
- resources/js/components/pages/create/CreateFuelTank.vue
Enhancement, Bug fix, Dependencies
___
- Simplified the `MultiCheckbox` component by removing unnecessary class bindings and making the `label` prop optional.
- Updated the `Popover` component to remove an unused `hover` prop and added dark mode styles.
- Added a new `Toggle` component with switch functionality.
- Integrated the new `Toggle` component into the `CreateFuelTank` page for account management and updated the logic for fuel tank flags.
- Updated Vue and related dependencies to the latest versions in `package-lock.json` and `package.json`.
___
<tr>
<td>
<details>
<summary><strong>MultiCheckbox.vue</strong><dd><code>Simplify MultiCheckbox …
> [PLA-1793] fueltank checkbox

- resources/js/components/App.vue
Bug fix
___
- Added a condition in `App.vue` to check if the user is logged in and if the wallet exists before attempting to load the wallet. This prevents the wallet connection modal from randomly popping up.
___
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Fix random wallet connection modal popup issue</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Added a condition to check if the user is logged in and if the wallet <br>exists before loading the wallet.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/136/files#diff-27b19 …
> [PLA-1903] fix wc modal random popup

- resources/js/components/pages/Settings.vue
Enhancement
___
- Capitalized the title of the API Tokens tab in the Settings page.
- Capitalized the title of the Helpful Links tab in the Settings page.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Capitalize titles in Settings page components</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Capitalized the title of the API Tokens tab.<br> <li> Capitalized the title of the Helpful Links tab.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/139/files#diff-9408c437ed722b0b729de4bd17db6e76e40cd667 …
> [PLA-1908] capitalize settings texts

- resources/js/api/collection.ts
- resources/js/api/mutations.ts
- resources/js/components/NotificationsList.vue
- resources/js/components/TrackCollectionModal.vue
- resources/js/components/pages/Collections.vue
- resources/js/factory/collection.ts
- resources/js/graphql/mutation/TrackCollection.ts
- resources/js/graphql/mutation/UntrackCollection.ts
- resources/js/store/connection.ts
- vite.config.ts
___
- Added a new modal component (`TrackCollectionModal.vue`) for tracking collections.
- Integrated collection tracking functionality in the `Collections.vue` page, including buttons for tracking and untracking collections.
- Added API methods and GraphQL mutations for tracking and untracking collections.
- Updated the collection factory to include tracking status.
- Improved theming for the "No notifications" message in `NotificationsList.vue`.
- Fixed a bug in `connection.ts` to set user accounts only if multi-tenant mode is enabled.
- Configured the development server to run on port 5174 in `vite.config.ts`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 …
> [PLA-1911] collection tracking

- resources/js/components/pages/create/CreateToken.vue
- resources/js/types/types.enums.ts
Enhancement
___
- Added a new `Supply Cap` section in the token creation form, allowing users to set a maximum supply for tokens.
- Introduced a `Supply Cap Type` dropdown with options including `INFINITE`, `COLLAPSING_SUPPLY`, and `SINGLE_MINT`.
- Updated the token creation logic to utilize the new `capType` value.
- Implemented a `watch` function to reset `capType` based on the selected `tokenType`.
- Added `COLLAPSING_SUPPLY` to the `TokenCapType` enum in the TypeScript types file.
___
<tr>
<td>
<details>
<summary><strong>CreateToken.vue</strong><dd><code>Add supply cap options for token creation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> [PLA-1920] supply cap token

- resources/js/components/Popover.vue
Bug fix
___
- Added the `hover` prop to the `Popover` component in `Popover.vue` to fix the notifications hover box issue.
___
<tr>
<td>
<details>
<summary><strong>Popover.vue</strong><dd><code>Add hover prop to Popover component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/Popover.vue
- Added `hover` prop to the Popover component.
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/144/files#diff-a1932e69695f960fbcbda36f2b7fa10fc2fb769f9be801e24803ea4ddce3bfe4">+1/-0</a>&nbsp; …
> [PLA-1916] fix notifications hover box

- resources/js/components/App.vue
- resources/js/components/pages/Collections.vue
- resources/js/factory/collection.ts
- resources/js/store/connection.ts
___
- Enhanced wallet loading and account fetching by making the `setTimeout` callback asynchronous and increasing the timeout duration.
- Fixed and enhanced collection tracking logic to include daemon account and additional account checks.
- Added return statement for `getAccounts` method in `useConnectionStore`.
___
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Enhance wallet loading and account fetching on mount</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Changed <code>setTimeout</code> callback to be asynchronous.<br> <li> Added call to <code>getAccounts</code> …
> [PLA-1911] fix collection tracking

- resources/js/components/ReadMoreButton.vue
- resources/js/components/pages/create/CreateToken.vue
___
- Enhanced the `ReadMoreButton` component to handle URLs by opening them in a new tab, improving user navigation.
- Fixed CSS class application for token type selection in `CreateToken.vue`, ensuring correct styling.
- Updated supply cap logic to include a new cap type and adjusted conditional logic based on network configuration, addressing supply cap issues.
___
<tr>
<td>
<details>
<summary><strong>ReadMoreButton.vue</strong><dd><code>Add URL handling for ReadMoreButton component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> [PLA-1920] supply cap fix

- resources/js/store/index.ts
bug_fix
___
- Improved error handling in the `login` function by adding optional chaining for `res.errors` to prevent potential runtime errors.
- Modified the logic to return `false` instead of throwing an error when login credentials are invalid.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Improve error handling in login function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/store/index.ts
<li>Added optional chaining for <code>res.errors</code> to prevent potential runtime <br>errors.<br> <li> Changed the error handling …
> [PLA-1786] fix login text

- .github/workflows/deploy.yml
- resources/js/components/App.vue
- resources/js/components/CollapseCard.vue
- resources/js/components/NotificationsList.vue
- resources/js/components/SignTransaction.vue
- resources/js/components/Snackbar.vue
- resources/js/components/SnackbarGroup.vue
- resources/js/components/UserNavbar.vue
- resources/js/components/WalletConnectButton.vue
- resources/js/components/pages/Collections.vue
- resources/js/components/pages/Settings.vue
- resources/js/components/pages/SettingsWalletApp.vue
- resources/js/components/pages/SettingsWalletDaemon.vue
- resources/js/types/types.interface.ts
- resources/js/util/auth.guard.ts
- resources/js/util/snackbar.ts
___
- Enhanced the settings page by adding new components for wallet management: `SettingsWalletApp` and `SettingsWalletDaemon`.
- Improved notification handling by adding transaction redirection and Slideover component in `NotificationsList`.
- Updated `SignTransaction` component to provide a link for wallet configuration in error messages.
- Simplified conditions and removed redundant code in multiple components for better performance and readability.
- Added support for links in notifications across various components.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Update …
> [PLA-1917] settings redesign

- resources/js/components/pages/SettingsWalletDaemon.vue
Bug fix
___
- Fixed a bug in the `SettingsWalletDaemon.vue` file where the message for configuring a new Daemon wallet was incorrectly displayed based on the `isMultiTenant` condition.
- The condition was changed from `!isMultiTenant` to `isMultiTenant` to ensure the message is shown only in a multi-tenant environment.
___
<tr>
<td>
<details>
<summary><strong>SettingsWalletDaemon.vue</strong><dd><code>Corrected conditional rendering for multi-tenant settings</code></dd></summary>
<hr>
resources/js/components/pages/SettingsWalletDaemon.vue
<li>Fixed the condition for displaying the API token configuration <br>message.<br> <li> Changed the <code>v-if</code> …
> [PLA-1917] fix settings page

- resources/js/components/pages/create/CreateToken.vue
enhancement
___
- Enhanced the token creation form by adding a new input field for `decimalsCount` to specify the number of decimal places for the token.
- Moved the `symbol` input field to a different section in the form for better organization.
- Updated the validation schema to include `decimalsCount` and made `symbol` optional.
- Included `decimalCount` in the token metadata creation process to support the new feature.
___
<tr>
<td>
<details>
<summary><strong>CreateToken.vue</strong><dd><code>Enhance token creation form with decimal support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> [PLA-2048] add symbol and decimal to token creation

- resources/js/components/InputHeader.vue
- resources/js/components/ReadMoreButton.vue
- resources/js/components/pages/create/CreateToken.vue
enhancement
___
- Enhanced the `InputHeader` component by restructuring the layout and improving conditional rendering for labels and tooltips.
- Updated the `ReadMoreButton` component text from "Read more" to "Learn more" for better user understanding.
- Overhauled the `CreateToken` component to replace token type selection with new fields for quantity and maximum supply, including toggles for setting maximum supply and allowing re-minting.
- Adjusted validation schema and computed properties to align with the new token creation logic, removing outdated token type and supply cap logic.
___
<tr>
<td>
<details> …
> [PLA-2028] update token create

- resources/js/components/slideovers/token/BurnTokenSlideover.vue
enhancement
___
- Enhanced the `BurnTokenSlideover` component by adding a dynamic description to the `amount` input field, indicating the maximum amount that can be burned based on the `supply` property.
- Introduced a new `supply` property to the `item` object in the component's props to support the dynamic description feature.
___
<tr>
<td>
<details>
<summary><strong>BurnTokenSlideover.vue</strong><dd><code>Enhance BurnTokenSlideover with dynamic amount description</code></dd></summary>
<hr>
resources/js/components/slideovers/token/BurnTokenSlideover.vue
<li>Enhanced the <code>FormInput</code> component to include a dynamic description for <br>the …
> [PLA-1840] add supply to form

- resources/js/components/RichTextEditor.vue
- resources/js/components/pages/create/CreateBeam.vue
Bug fix
___
- Fixed dark mode styling inconsistencies in the `RichTextEditor` component by updating CSS classes for background and border styles.
- Improved error messaging in the `CreateBeam` component to provide specific feedback for invalid beam assets during form validation.
___
<tr>
<td>
<details>
<summary><strong>RichTextEditor.vue</strong><dd><code>Fix dark mode styling inconsistencies in RichTextEditor</code>&nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/RichTextEditor.vue
<li>Updated CSS classes for dark mode styling in the editor toolbar.<br> <li> Adjusted background and border styles for consistency in dark mode.<br>
</details>
</td> …
> [PLA-1825] fix beam error text

- resources/js/api/transaction.ts
- resources/js/components/SignTransaction.vue
- resources/js/graphql/query/GetWallets.ts
- resources/js/store/connection.ts
Enhancement
___
- Added functionality to fetch and display wallet balances for accounts in the transaction signing process.
- Introduced a new method `fetchAccountsBalance` in `SignTransaction.vue` to retrieve balances via API.
- Updated the `getWallets` API method and `GetWallets` GraphQL query to support filtering by specific accounts.
- Enhanced the connection store with a new method `setAccountsBalance` to manage account balances.
- Improved the user interface to show wallet balances alongside account details during transaction signing.
___
<tr>
<td>
<details>
<summary><strong>SignTransaction.vue</strong><dd><code>Add wallet balance fetching and …
> [PLA-1836] add wallet balance for signing

- resources/js/components/marketplace/BidsList.vue
- resources/js/components/marketplace/ListingsList.vue
- resources/js/components/marketplace/SalesList.vue
- resources/js/components/pages/Collections.vue
- resources/js/components/pages/FuelTanks.vue
- resources/js/components/pages/Tokens.vue
- resources/js/components/pages/Transactions.vue
Enhancement
___
- Added sorting functionality to the `Collections`, `Fuel Tanks`, and `Tokens` tables.
- Introduced `sortKey` and `sortOrder` state variables to manage sorting logic across all tables.
- Implemented computed properties (`sortedCollections`, `sortedFuelTanks`, and `sortedTokens`) to dynamically sort data based on the selected column and order.
- Enhanced table headers with click events for sorting and visual indicators (arrows) to show the current sorting state.
___
<tr>
<td>
<details>
<summary><strong>Collections.vue</strong><dd><code>Add sorting functionality to Collections table columns.</code>&nbsp; &nbsp; </dd></summary>
<hr> …
> [PLA-2109] tables column sorting

- resources/js/components/FormSelect.vue
- resources/js/components/beam/ClaimsList.vue
- resources/js/components/pages/Collections.vue
- resources/js/components/pages/FuelTanks.vue
- resources/js/components/slideovers/beam/ClaimBeamSlideover.vue
- resources/js/components/slideovers/fueltank/DetailsFuelTankSlideover.vue
- resources/js/components/slideovers/fueltank/FreezeFuelTankSlideover.vue
- resources/js/components/slideovers/token/BurnTokenSlideover.vue
- resources/js/util/index.ts
___
- Fixed fuel tank freeze/unfreeze functionality and terminology.
- Enhanced claim list with new "Claim Status" column.
- Improved token validation and burn functionality.
- Updated QR code rendering and collection search logic.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
<td><strong>FormSelect.vue</strong><dd><code>Added default value initialization for select component.</code>&nbsp; </dd></td>
<td><a href="https://github.com/enjin/platform-ui/pull/186/files#diff-568abbf78a911b66e4c9450b3fd874438dcb150be35f274ab7f865ca06210e30">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
<tr>
<td><strong>ClaimsList.vue</strong><dd><code>Added "Claim …
> [PLA-2075] [PLA-1856] [PLA-2129] [PLA-2081] [PLA-1918] bug fixes

- package-lock.json
- package.json
- resources/js/api/index.ts
- resources/js/components/WalletConnectButton.vue
- resources/js/store/connection.ts
- resources/js/store/transaction.ts
___
- Added support for MetaMask Snap integration with Enjin Connect.
- Introduced `EnjinConnectSnap` class for MetaMask wallet handling.
- Updated wallet connection logic to support Enjin Snap.
- Fixed transaction payload specVersion and transactionVersion formatting.
___
<tr>
<td>
<details>
<summary><strong>WalletConnectButton.vue</strong><dd><code>Add MetaMask connection button in WalletConnect</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/WalletConnectButton.vue
<li>Added a new button for MetaMask connection.<br> <li> Integrated <code>connectWallet</code> …
> feat: PLA-284 Add Metamask snap support

- resources/js/components/WalletConnectButton.vue
- resources/js/components/pages/SettingsWalletApp.vue
Bug fix
___
- Fixed incorrect wallet name mapping for MetaMask.
- Added condition to handle `enjin-connect` provider.
___
<tr>
<td>
<details>
<summary><strong>WalletConnectButton.vue</strong><dd><code>Fix wallet name logic for MetaMask</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/WalletConnectButton.vue
<li>Added a condition to map <code>enjin-connect</code> provider to 'MetaMask'.<br> <li> Ensured correct wallet name is returned for MetaMask.
</details>
</td>
<td><a …
> fix: walletName for MetaMask
