enjin/platform-ui

resources/js/api/index.ts, resources/js/components/pages/Settings.vue, resources/js/store/index.ts
enhancement
___
- Made `reloadCsrf` method in `ApiService` public and enhanced its implementation to fetch and parse CSRF token.
- Integrated CSRF token refresh in login, logout, and account deletion flows to enhance security.
- This ensures that the CSRF token is refreshed at critical points, improving the application's security posture.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Integrate CSRF Token Refresh in Settings Page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Imported <code>ApiService</code> from …
=> [PLA-1714] Add refresh csrf token

resources/js/components/ConfirmModal.vue, resources/js/components/pages/SettingsResetPassword.vue, resources/js/components/pages/Transactions.vue
___
- Introduced enhancements to UI alignment and clarity in button texts across ConfirmModal and SettingsResetPassword components.
- Significantly enhanced the Transactions page by adding dropdown menus for transaction actions and modals for retrying and canceling transactions, including the necessary API integration and feedback mechanisms.
___
<tr>
<td>
<details>
<summary><strong>ConfirmModal.vue</strong><dd><code>Improved Button Alignment in Confirm Modal</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/ConfirmModal.vue …
=> [PLA-1707] update transaction status

resources/js/graphql/query/auth/Login.ts
Bug fix
___
- Updated the GraphQL `Login` query in `Login.ts` to make the `recaptcha` parameter optional, enhancing the flexibility of the login functionality.
___
<tr>
<td>
<details>
<summary><strong>Login.ts</strong><dd><code>Update GraphQL Login Query to Make Recaptcha Optional</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/graphql/query/auth/Login.ts
<li>Made the <code>recaptcha</code> parameter optional in the GraphQL <code>Login</code> query.<br> <li> Updated the <code>recaptcha</code> parameter name in the <code>Login</code> function call.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/98/files#diff-51e …
=> [PLA-1727] fix login query

resources/js/api/index.ts, resources/js/components/batch/BatchMint.vue, resources/js/components/pages/Collections.vue, resources/js/components/pages/Settings.vue, resources/js/components/pages/SettingsResetPassword.vue, resources/js/components/pages/auth/RequestResetPassword.vue, resources/js/components/pages/auth/ResetPassword.vue, resources/js/graphql/mutation/auth/RequestPasswordReset.ts, resources/js/store/index.ts
___
- Enhanced error handling and user feedback mechanisms in password reset functionalities.
- Refactored API error handling to provide clearer and more specific error messages.
- Simplified the `RequestPasswordReset` mutation by removing unnecessary parameters.
- Improved code readability and structure across various components and store configurations.
___
<tr>
<td>
<details>
<summary><strong>RequestResetPassword.vue</strong><dd><code>Enhance Error Handling and Feedback in Password Reset</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/auth/RequestResetPassword.vue
<li>Improved error handling …
=> [PLA-1740] bad request 400 error handling

resources/js/api/beam.ts, resources/js/components/slideovers/beam/DetailsBeamSlideover.vue, resources/js/components/slideovers/beam/UpdateBeamSlideover.vue, resources/js/graphql/mutation/beam/UpdateBeam.ts, resources/js/graphql/query/beam/GetBeam.ts, resources/js/graphql/query/beam/GetBeams.ts
___
- Added UI components and API support for displaying and updating claim conditions in beam details.
- Enhanced GraphQL queries and mutations to handle claim conditions, allowing for better data management and display.
- Updated Vue components to integrate claim conditions into the existing beam management system.
___
<tr>
<td>
<details>
<summary><strong>DetailsBeamSlideover.vue</strong><dd><code>Add Claim Conditions Display in DetailsBeamSlideover</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/slideovers/beam/DetailsBeamSlideover.vue
<li>Added a new section to display claim conditions in the …
=> [PLA-1756] add claim conditions view

resources/js/components/slideovers/fueltank/ConsumptionFuelTankSlideover.vue, resources/js/components/slideovers/fueltank/MutateFuelTankSlideover.vue
___
- Updated the `userId` field to be optional in `ConsumptionFuelTankSlideover.vue`, enhancing flexibility in user ID handling.
- Refactored and enhanced the validation schemas in `MutateFuelTankSlideover.vue`, including changes to boolean fields and array handling for `whitelistedCallers`.
- Improved data formatting for token IDs and caller lists, ensuring better data integrity and error handling.
___
<tr>
<td>
<details>
<summary><strong>ConsumptionFuelTankSlideover.vue</strong><dd><code>Update validation schema for ConsumptionFuelTank</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> [PLA-1758] fix fuel tank

config/enjin-platform-ui.php, package-lock.json, package.json, resources/js/components/FormSelect.vue, resources/js/components/batch/forms/BatchMintForm.vue, resources/js/components/batch/forms/BatchTransferForm.vue, resources/js/components/fueltank/DispatchRuleForm.vue, resources/js/components/slideovers/beam/ClaimBeamSlideover.vue, resources/js/components/slideovers/beam/UpdateBeamSlideover.vue, resources/js/components/slideovers/common/DetailsTransactionSlideover.vue, resources/js/components/slideovers/common/FreezeSlideover.vue, resources/js/components/slideovers/common/ThawSlideover.vue, resources/js/components/slideovers/fueltank/AccountsFuelTankSlideover.vue, resources/js/components/slideovers/fueltank/ConsumptionFuelTankSlideover.vue, resources/js/components/slideovers/fueltank/DispatchFuelTankSlideover.vue, resources/js/components/slideovers/fueltank/FreezeFuelTankSlideover.vue, resources/js/components/slideovers/fueltank/MutateFuelTankSlideover.vue, resources/js/components/slideovers/fueltank/RuleSetsFuelTankSlideover.vue, resources/js/components/slideovers/token/ApproveTokenSlideover.vue, resources/js/components/slideovers/token/AttributesTokenSlideover.vue, resources/js/components/slideovers/token/BurnTokenSlideover.vue, resources/js/components/slideovers/token/MintTokenSlideover.vue, resources/js/components/slideovers/token/MutateTokenSlideover.vue, resources/js/components/slideovers/token/TransferTokenSlideover.vue, resources/js/components/slideovers/token/UnapproveTokenSlideover.vue, resources/js/store/index.ts
___
- Enhanced several Vue components by adding non-null assertions and required validations to improve form handling and prevent runtime errors.
- Added error handling and UI improvements in `DispatchRuleForm` and `RuleSetsFuelTankSlideover`.
- Updated `package.json` and `package-lock.json` to include lodash as a dependency.
___
</strong></td><td><details><summary>4 files</summary><table>
<tr>
<td>
<details>
<summary><strong>FormSelect.vue</strong><dd><code>Refactor FormSelect component for improved usability</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/FormSelect.vue
<li>Removed dynamic class binding and added static …
=> [PLA-1762] form fixes

resources/js/components/pages/create/CreateCollection.vue, resources/js/components/pages/create/CreateToken.vue
enhancement
___
- Added and reorganized `FormInput` components for better user input structure in both collection and token creation forms.
- Updated validation schemas to improve form validation logic, making some fields not required and refining error messages.
- Adjusted the descriptions in `RichTextEditor` components to match the context of tokens and collections.
___
<tr>
<td>
<details>
<summary><strong>CreateCollection.vue</strong><dd><code>Enhance Form Inputs and Validation in CreateCollection</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/create/CreateCollection.vue
<li>Added a new <code>FormInput</code> for the …
=> [PLA-1731] text fixes

resources/js/api/auth.ts, resources/js/components/Modal.vue, resources/js/components/pages/Settings.vue, resources/js/components/pages/SettingsChangeEmail.vue, resources/js/components/pages/VerifyPasswordModal.vue, resources/js/graphql/mutation/auth/DeleteAccount.ts, resources/js/graphql/mutation/auth/UpdateUser.ts, resources/js/router/index.ts
___
- Updated `Modal` component to change `close` prop type to `Function` and modified its usage.
- Integrated `VerifyPasswordModal` component in `Settings` and `SettingsChangeEmail` pages for password verification.
- Created a new `VerifyPasswordModal` component to handle password verification with optional reCAPTCHA.
- Simplified route redirection logic for beams and marketplace in the router configuration.
___
<tr>
<td>
<details>
<summary><strong>Modal.vue</strong><dd><code>Update `close` prop type and usage in Modal component</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/Modal.vue
<li>Changed …
=> [PLA-1766] require password settings

resources/js/api/marketplace.ts, resources/js/api/queries.ts, resources/js/components/Chip.vue, resources/js/components/CollapseFilter.vue, resources/js/components/Popover.vue, resources/js/components/pages/create/CreateListing.vue, resources/js/graphql/mutation/marketplace/CreateListing.ts, resources/js/graphql/query/marketplace/GetBlocks.ts
___
- Updated `Chip.vue` to fix background color class binding for non-error states.
- Modified `CollapseFilter.vue` to use dynamic theme from `useAppStore`.
- Added `--popper-theme-padding` CSS variable in `Popover.vue`.
- Enhanced `CreateListing.vue` by adding auction functionality, removing the `account` field, and updating validation schema.
- Updated `marketplace.ts` to remove `account` from `createListing` and added `getCurrentBlock` method.
- Added `GetBlocks` query to `queries.ts` and `GetBlocks.ts`.
- Removed `account` parameter from `CreateListing` mutation.
___
<tr>
<td>
<details> …
=> [PLA-1772] fix marketplace listing

resources/js/components/pages/VerifyPasswordModal.vue, resources/js/store/index.ts
___
- Removed reCAPTCHA functionality from `VerifyPasswordModal.vue`.
- Updated the `confirm` method in `VerifyPasswordModal.vue` to call `AuthApi.updateUser` instead of `AuthApi.login`.
- Simplified the modal confirmation process in `VerifyPasswordModal.vue`.
- Fixed the logic in `index.ts` to limit the total count of collection IDs fetched to a maximum of 500.
___
<tr>
<td>
<details>
<summary><strong>VerifyPasswordModal.vue</strong><dd><code>Remove reCAPTCHA and update password confirmation logic.</code>&nbsp; </dd></summary>
<hr>
resources/js/components/pages/VerifyPasswordModal.vue
<li>Removed reCAPTCHA functionality.<br> <li> …
=> [PLA-1781] update password query

resources/js/components/beam/BeamsList.vue, resources/js/components/beam/ClaimsList.vue, resources/js/components/marketplace/BidsList.vue, resources/js/components/marketplace/ListingsList.vue, resources/js/components/marketplace/SalesList.vue, resources/js/components/pages/Collections.vue, resources/js/components/pages/FuelTanks.vue, resources/js/components/pages/Tokens.vue, resources/js/components/pages/Transactions.vue, resources/js/components/pages/Wallets.vue, resources/js/components/pages/auth/Login.vue, resources/js/store/index.ts
Bug fix
___
- Added calls to `clearInitPromise` after `initPromise` is awaited in various components to ensure the promise is cleared after initialization.
- Added `clearInitPromise` method in the store to facilitate clearing the `initPromise`.
___
</strong></td><td><details><summary>12 files</summary><table>
<tr>
<td>
<details>
<summary><strong>BeamsList.vue</strong><dd><code>Clear initPromise after initialization in BeamsList</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/beam/BeamsList.vue
- Added call to `clearInitPromise` after `initPromise` is awaited.
</details>
</td>
<td><a …
=> hotfix: clear promise call

resources/js/components/App.vue, resources/js/components/beam/BeamsList.vue, resources/js/components/beam/ClaimsList.vue, resources/js/components/marketplace/BidsList.vue, resources/js/components/marketplace/ListingsList.vue, resources/js/components/marketplace/SalesList.vue, resources/js/components/pages/Collections.vue, resources/js/components/pages/FuelTanks.vue, resources/js/components/pages/Tokens.vue, resources/js/components/pages/Transactions.vue, resources/js/components/pages/Wallets.vue, resources/js/components/pages/auth/Login.vue, resources/js/store/index.ts
___
- Changed initialization to await `appStore.init()` in multiple components.
- Removed usage of `initPromise` and `clearInitPromise` from various components.
- Refactored `init` method in `store/index.ts` to simplify initialization logic.
___
</strong></td><td><details><summary>3 files</summary><table>
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Await `appStore.init()` during initialization.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Changed initialization to await `appStore.init()`.
</details>
</td>
<td><a …
=> [PLA-1785] remove init promise

resources/js/components/marketplace/SalesList.vue, resources/js/components/slideovers/marketplace/DetailsSaleSlideover.vue, resources/js/graphql/query/marketplace/GetSales.ts, resources/js/util/index.ts
Bug fix
___
- Removed 'Listing' column and related data from the SalesList component.
- Removed 'Listing' section from the DetailsSaleSlideover component.
- Removed 'listing' field from the GetSales GraphQL query.
- Added null check for 'listing' in the checkFormatPrice function.
___
<tr>
<td>
<details>
<summary><strong>SalesList.vue</strong><dd><code>Remove 'Listing' column and related data from SalesList component.</code></dd></summary>
<hr>
resources/js/components/marketplace/SalesList.vue
<li>Removed 'Listing' column from the sales list table.<br> <li> Removed the corresponding data cell for 'Listing' in the table body.<br> <li> Removed 'listingIds' from …
=> [PLA-1809] fix sales page

resources/js/components/App.vue, resources/js/components/SignTransaction.vue, resources/js/components/slideovers/common/DetailsTransactionSlideover.vue
Bug fix
___
- Adjusted the initialization order in `App.vue` to ensure the theme is set before initializing the app store.
- Fixed dark mode text color issues in `SignTransaction.vue` by adding appropriate dark mode classes.
- Fixed dark mode text color issues in `DetailsTransactionSlideover.vue` by adding appropriate dark mode classes.
___
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Adjust initialization order for theme and app store</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Moved `initialTheme()` call before `appStore.init()`
</details>
</td>
<td><a …
=> [PLA-1779] fix darkmode ui

resources/js/components/beam/BeamsList.vue, resources/js/store/index.ts
Bug fix
___
- Added a call to `appStore.fetchInternal()` in `BeamsList.vue` before fetching beam codes to ensure internal configuration is fetched.
- Introduced a new method `fetchInternal` in the app store to fetch and update internal configuration.
___
<tr>
<td>
<details>
<summary><strong>BeamsList.vue</strong><dd><code>Add internal fetch before beam codes retrieval</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/beam/BeamsList.vue
<li>Added a call to <code>appStore.fetchInternal()</code> before fetching beam codes.<br>
</details>
</td>
<td><a …
=> [PLA-1783] fix internal beams query

resources/js/components/pages/create/CreateCollection.vue, resources/js/components/pages/create/CreateToken.vue
Bug fix
___
- Fixed the handling of the `media` attribute in both `CreateCollection.vue` and `CreateToken.vue` to ensure it is properly stringified or set to an empty string.
- Corrected the merging of `simpleAttributes` and `attributes` in both `CreateCollection.vue` and `CreateToken.vue` to avoid nested arrays.
___
<tr>
<td>
<details>
<summary><strong>CreateCollection.vue</strong><dd><code>Fix media attribute handling and attributes merging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/create/CreateCollection.vue
<li>Fixed the handling of the <code>media</code> attribute to ensure it is properly …
=> [PLA-1824] fix token creation

resources/js/api/index.ts, resources/js/components/pages/Collections.vue, resources/js/components/pages/Tokens.vue, resources/js/store/index.ts
Enhancement
___
- Added new columns for displaying collection and token names in the respective tables.
- Implemented methods to fetch and display names for collections and tokens.
- Added a new method `fetchUrl` in the `ApiService` to fetch data from a given URL.
- Renamed `fetchURL` to `fetchPlatformURL` and updated its usage in the store.
___
<tr>
<td>
<details>
<summary><strong>Collections.vue</strong><dd><code>Add and display collection names in Collections table.</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/Collections.vue
<li>Added a new column for collection names in the table.<br> <li> Implemented logic to fetch …
=> [PLA-1648] add token collection name

resources/js/components/SupportButton.vue, resources/js/components/beam/BeamsList.vue, resources/js/components/pages/create/CreateCollection.vue, resources/js/components/pages/create/CreateFuelTank.vue, resources/js/components/pages/create/CreateToken.vue, resources/js/components/slideovers/beam/ClaimBeamSlideover.vue, resources/js/components/slideovers/beam/DetailsBeamSlideover.vue, resources/js/components/slideovers/marketplace/DetailsListingSlideover.vue, resources/js/graphql/query/GetCollectionIds.ts, resources/js/store/index.ts
___
- Added dark mode support to `QuestionMarkCircleIcon` in multiple components.
- Reformatted `Btn` components in `BeamsList.vue` for better readability.
- Adjusted class for better alignment of `dd` element in `ClaimBeamSlideover.vue`.
- Added null checks for `item.flags` and `item.claimConditions` in `DetailsBeamSlideover.vue`.
- Fixed typo in GraphQL query name in `GetCollectionIds.ts`.
- Fixed typo in invalid credentials error message in `index.ts`.
___
</strong></td><td><details><summary>7 files</summary><table>
<tr>
<td>
<details>
<summary><strong>SupportButton.vue</strong><dd><code>Add dark mode support for `QuestionMarkCircleIcon`.</code>&nbsp; …
=> [PLA-1779] darkmode fixes

resources/js/api/index.ts, resources/js/components/pages/Settings.vue, resources/js/store/index.ts, resources/views/app.blade.php
___
- Removed CSRF token handling from the API service, simplifying request logic.
- Eliminated calls to `ApiService.reloadCsrf` in various parts of the application, including during login, logout, and account deletion.
- Removed the CSRF token meta tag from the HTML head.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Remove CSRF reload call after account deletion.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Removed call to `ApiService.reloadCsrf` after account deletion.
</details>
</td>
<td><a …
=> [PLA-1864] Remove csrf cookie meta and use cookie instead

resources/js/api/index.ts, resources/js/components/pages/Settings.vue, resources/js/store/index.ts, resources/views/app.blade.php
Reverts enjin/platform-ui#127
___
___
- Added import and usage of `ApiService.reloadCsrf()` in various components to ensure CSRF token is reloaded after critical actions like account deletion, login, and logout.
- Modified API service to include CSRF token in headers for multi-tenant requests and to handle 419 status by reloading the CSRF token and retrying the request.
- Added meta tag for CSRF token in the HTML head to facilitate CSRF protection.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Add CSRF token reload after account deletion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Revert "[PLA-1864] Remove csrf cookie meta and use cookie instead"

resources/js/components/pages/create/CreateBeam.vue
Bug fix
___
- Added a snackbar error message to inform users when form validation fails in the `CreateBeam` component.
___
<tr>
<td>
<details>
<summary><strong>CreateBeam.vue</strong><dd><code>Add error message for form validation failure in CreateBeam</code></dd></summary>
<hr>
resources/js/components/pages/create/CreateBeam.vue
- Added error message display for form validation failure.
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/133/files#diff-108f2dfc73ef5f3491391c05c1f223a12618e1ecf9b024d4f8602924dc694046">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>
___
> 💡 **PR-Agent …
=> [PLA-1825] fix create beam error message

resources/js/components/FormInput.vue, resources/js/components/pages/SettingsWalletAccount.vue, resources/js/graphql/query/auth/User.ts
___
- Enhanced the wallet account display in `SettingsWalletAccount.vue` by adding labels for wallet accounts with copy-to-clipboard functionality.
- Updated the layout to display connected wallets and introduced a `copyText` method to handle clipboard copying.
- Modified `walletAccount` and `userWalletAccounts` computations to support multi-tenant configurations.
- Added the `walletAccounts` field to the User GraphQL query in `User.ts`.
- Fixed a minor issue by removing a redundant space in the class binding in `FormInput.vue`.
___
<tr>
<td>
<details>
<summary><strong>FormInput.vue</strong><dd><code>Remove redundant space in class …
=> [PLA-1906] add wallet accounts

resources/js/factory/collection.ts
Bug fix
___
- Fixed the logic for tracking collections by changing the method from `some` to `find` for account comparison.
- Added conversion of public key to address using `publicKeyToAddress` function to ensure proper comparison.
___
<tr>
<td>
<details>
<summary><strong>collection.ts</strong><dd><code>Fix account tracking logic in collection factory</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/factory/collection.ts
<li>Changed <code>some</code> method to <code>find</code> method for account comparison.<br> <li> Utilized <code>publicKeyToAddress</code> function for public key conversion.<br> …
=> [PLA-1911] fix collection tracked

resources/js/components/TrackCollectionModal.vue, resources/js/components/pages/SettingsWalletAccount.vue
Bug fix
___
- Fixed the conditional rendering logic in `SettingsWalletAccount.vue` by changing `v-else-if` to `v-if` for displaying connected wallets.
___
<tr>
<td>
<details>
<summary><strong>SettingsWalletAccount.vue</strong><dd><code>Fix conditional rendering for connected wallets display</code>&nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/SettingsWalletAccount.vue
<li>Changed <code>v-else-if</code> directive to <code>v-if</code> for displaying connected wallets.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/142/files#diff-517813456ec5d4b4d3d8a79c7b8678f9915d46a6bc1485a82349b3d8e2f938b0">+1/-1</a>&nbsp; …
=> [PLA-1906] fix wallet texts

resources/js/graphql/query/auth/User.ts
Bug fix
___
- Removed the `walletAccounts` field from the User query in the `resources/js/graphql/query/auth/User.ts` file.
___
<tr>
<td>
<details>
<summary><strong>User.ts</strong><dd><code>Remove `walletAccounts` field from User query</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/graphql/query/auth/User.ts
- Removed the `walletAccounts` field from the User query.
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/145/files#diff-d13a1327e2c72bd7774e7924a40a58f242640508b5504a50128d672b021d13ed">+0/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> hotfix: fix user query

resources/js/components/SignTransaction.vue
Enhancement
___
- Added a new section in the `SignTransaction.vue` component to display the deposit fee.
- Introduced a new reactive variable `deposit` to handle the deposit fee.
- Updated the `signTransaction` function to calculate and set the deposit fee.
___
<tr>
<td>
<details>
<summary><strong>SignTransaction.vue</strong><dd><code>Add deposit fee display in transaction summary</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/SignTransaction.vue
<li>Added a new section to display the deposit fee in the transaction <br>summary.<br> <li> Introduced a new reactive variable …
=> [PLA-1925] add deposit fee

vite.config.laravel.ts, vite.config.ts
Bug fix
___
- Removed the definition of `process.env` in `vite.config.laravel.ts` and `vite.config.ts`.
- Simplified the Vite configuration by eliminating unnecessary code.
___
<tr>
<td>
<details>
<summary><strong>vite.config.laravel.ts</strong><dd><code>Remove `process.env` definition from Vite config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
vite.config.laravel.ts
<li>Removed the definition of <code>process.env</code> in the Vite configuration.<br> <li> Simplified the configuration by eliminating unnecessary code.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/149/files#diff-3aade3c …
=> [PLA-1929] Removes defining process.env in vite configs.

resources/js/components/App.vue, resources/js/components/DropdownMenu.vue, resources/js/components/TransactionResultChip.vue, resources/js/components/pages/Collections.vue, resources/js/factory/collection.ts
Bug fix
___
- Improved the logic for tracking collections by consolidating and enhancing account checks.
- Added user account and daemon account to the list of accounts to be checked for tracking.
- Ensured that only unique accounts are considered when determining if a collection is tracked.
___
<tr>
<td>
<details>
<summary><strong>collection.ts</strong><dd><code>Refactor and enhance collection tracking logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/factory/collection.ts
<li>Improved logic for tracking collections by consolidating account <br>checks.<br> <li> Added user account and …
=> [PLA-1911] improve collection tracking check

resources/js/factory/collection.ts
Bug fix
___
- Added a condition to check `appStore.isMultiTenant` before pushing the daemon account in `DTOCollectionFactory`.
- This fix ensures that the daemon account is not tracked in multi-tenant setups.
___
<tr>
<td>
<details>
<summary><strong>collection.ts</strong><dd><code>Fix daemon account tracking for multi-tenant setups</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/factory/collection.ts
<li>Added a condition to check <code>appStore.isMultiTenant</code> before pushing the <br>daemon account.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/151/files#diff-01445672db13264dbc1cebd0222d1ec1f …
=> [PLA-1911] fix tracking with daemon account

resources/js/components/pages/Collections.vue
___
- Adjusted the position of the `Tracked` chip to be absolute and positioned at the top right.
- Corrected the description text in the `Untrack Collection` modal for better readability.
- Added success snackbar notifications for both tracking and untracking collections to improve user feedback.
___
<tr>
<td>
<details>
<summary><strong>Collections.vue</strong><dd><code>UI and UX improvements for tracking and untracking collections</code></dd></summary>
<hr>
resources/js/components/pages/Collections.vue
<li>Adjusted the position of the <code>Tracked</code> chip.<br> <li> Corrected the description text in the <code>Untrack …
=> [PLA-1934] tracking snackbar

resources/js/api/index.ts, resources/js/components/pages/Collections.vue, resources/js/components/pages/Tokens.vue
___
- Simplified JSON parsing logic in the `fetchUri` function within `Collections.vue` by directly checking the `name` property on the response object.
- Made the `mode` parameter optional in the `request` method of `ApiService` and adjusted CSRF token handling based on the `mode`.
- Standardized headers initialization in the `request` method.
- Ensured `mode` is set to 'cors' for GraphQL requests in `ApiService`.
___
<tr>
<td>
<details>
<summary><strong>Collections.vue</strong><dd><code>Simplify JSON parsing in fetchUri function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> [PLA-1936] fix metadata fetching

resources/js/components/FormInput.vue, resources/js/components/pages/Collections.vue, resources/js/components/pages/Tokens.vue
___
- Added a new slot for displaying error text in the `FormInput` component.
- Improved search input validation in `Collections.vue` and `Tokens.vue` to handle non-integer inputs.
- Fixed the logic for retrieving collection and token names to ensure proper fallback values.
- Removed redundant class attributes in `Collections.vue`.
___
<tr>
<td>
<details>
<summary><strong>FormInput.vue</strong><dd><code>Add slot for error text in FormInput component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/FormInput.vue
- Added a new slot for displaying error text. …
=> [PLA-1940] fix name missing

resources/js/api/index.ts, resources/js/store/index.ts, resources/js/types/types.interface.ts, src/Console/InstallPlatformUi.php, src/Console/RebuildPlatformUi.php, src/PlatformUiServiceProvider.php
___
- Fixed the retrieval of the authorization token in the `ApiService` by directly accessing `authorization_token` from `useAppStore`.
- Refactored the app store to remove redundant `authorization_token` from the `config` object and removed the `setAuthorizationToken` method.
- Updated the `AppState` interface to remove `authorization_token` from the `config`.
- Added a new method in `PlatformUiServiceProvider` to clear platform UI assets, ensuring old assets are removed before publishing new ones.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Fix authorization token retrieval in API service</code>&nbsp; &nbsp; …
=> [PLA-2007] self hosted auth

resources/js/api/collection.ts, resources/js/components/TrackCollectionModal.vue, resources/js/components/pages/Collections.vue, resources/js/graphql/mutation/TrackCollection.ts
___
- Added a `hotSync` parameter to the `trackCollection` method and its associated API call, allowing for conditional synchronization based on tenant configuration.
- Enhanced the `TrackCollectionModal` component by adding a loading state to the 'Track' button and adjusting the lifecycle hook to reset states on mount.
- Improved error handling in the `trackCollection` function by changing the snackbar message type to error on failure and ensuring the modal closes after an attempt.
- Updated the GraphQL mutation to include the `hotSync` parameter, enabling dynamic synchronization control.
___
<tr>
<td>
<details> …
=> [PLA-2011] collections hotsync

.github/workflows/deploy.yml, .github/workflows/lint.yml, resources/js/api/collection.ts, resources/js/api/index.ts, resources/js/components/FormInput.vue, resources/js/components/TrackCollectionModal.vue, resources/js/components/pages/Collections.vue, resources/js/components/pages/Tokens.vue, resources/js/components/pages/create/CreateToken.vue, resources/js/components/slideovers/token/MintTokenSlideover.vue, resources/js/graphql/mutation/TrackCollection.ts
___
- Enhanced `sendReadmoreEvent` in `ReadMoreButton.vue` to open URLs in a new tab if the `readmore` prop contains an HTTP link.
- Simplified `fetchUri` function in `Collections.vue` and `Tokens.vue` by directly using the response object and removing unnecessary JSON parsing.
- Updated token name cell styling in `Tokens.vue`.
- Added new form fields and logic for ENJ infusion in `CreateToken.vue`, including state variables for infusion options.
- Added `auth` parameter to API service methods in `index.ts`, updating headers logic to conditionally include authorization or CSRF token.
___
<tr>
<td>
<details> …
=> [PLA-1645] infuse token

resources/js/api/transaction.ts, resources/js/components/SideNavbar.vue, resources/js/components/pages/Collections.vue, resources/js/components/pages/Settings.vue, resources/js/components/pages/SettingsWalletDaemon.vue, resources/js/factory/collection.ts, resources/js/factory/transaction.ts, resources/js/graphql/query/GetCollectionIds.ts, resources/js/store/connection.ts, resources/js/store/index.ts
___
- Enhanced the sidebar navigation to display the transaction count, improving user awareness of pending transactions.
- Improved the collection tracking system by integrating account management, allowing for better tracking of user-specific collections.
- Simplified the wallet configuration display in the settings page, removing unnecessary logic.
- Enhanced the daemon wallet setup process with transitions and added API token management features for better user experience.
- Refactored transaction fetching to use a dynamic parameter, allowing for more flexible data retrieval.
- Removed redundant account tracking logic from the collection factory, streamlining the codebase.
- Added a new method to count pending transactions, providing more detailed transaction …
=> [PLA-2021] track fix

resources/js/components/SignTransaction.vue, resources/js/components/WalletConnectButton.vue, resources/js/components/pages/SettingsWalletApp.vue, resources/js/components/pages/WalletAppItem.vue, resources/js/components/pages/create/CreateCollection.vue, resources/js/store/connection.ts, resources/js/store/index.ts, resources/js/types/types.interface.ts
___
- Enhanced account management by introducing a computed property `walletAccounts` to filter enabled accounts and updating components to use this property.
- Added a new component `WalletAppItem` for managing wallet accounts, including enabling and disabling accounts.
- Fixed media array initialization in the collection creation process to prevent errors when image URLs are not present.
- Improved connection store by adding `disabledAccounts` state and methods to manage account enable/disable status.
- Ensured wallet accounts default to an empty array to prevent undefined errors.
___
<tr>
<td>
<details> …
=> [PLA-2020] wallet list sign

resources/js/components/pages/Settings.vue, resources/js/components/pages/SettingsHelp.vue
enhancement
___
- Introduced a new `SettingsHelp` component to encapsulate help text related to wallet configuration.
- Integrated the `SettingsHelp` component into the `Settings.vue` page, replacing the previous inline help text.
- Implemented toggle functionality in the `SettingsHelp` component to show or hide the help text with transition effects.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Integrate SettingsHelp component into Settings page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Replaced inline help text with a <code>SettingsHelp</code> …
=> [PLA-2020] add close action for help text in settings

.github/workflows/deploy.yml, .github/workflows/lint.yml, resources/js/api/collection.ts, resources/js/api/index.ts, resources/js/api/mutations.ts, resources/js/api/token.ts, resources/js/components/FormInput.vue, resources/js/components/WalletConnectButton.vue, resources/js/components/pages/Collections.vue, resources/js/components/pages/Tokens.vue, resources/js/components/pages/create/CreateCollection.vue, resources/js/components/pages/create/CreateToken.vue, resources/js/components/slideovers/collection/DetailsCollectionSlideover.vue, resources/js/components/slideovers/common/TransferBalanceSlideover.vue, resources/js/components/slideovers/token/DetailsTokenSlideover.vue, resources/js/components/slideovers/token/InfuseTokenSlideover.vue, resources/js/components/slideovers/token/MintTokenSlideover.vue, resources/js/graphql/mutation/TransferBalance.ts, resources/js/graphql/mutation/token/InfuseToken.ts, resources/js/graphql/query/GetCollection.ts, resources/js/graphql/query/GetCollections.ts, resources/js/graphql/query/GetTokens.ts, resources/js/store/index.ts
___
- Enhanced wallet connection logic to support multi-tenant environments.
- Simplified transfer balance logic by removing the `keepAlive` option.
- Removed display of `unitPrice` and `minimumBalance` in token details.
- Added pagination support to collection IDs fetching.
- Renamed and simplified the transfer balance mutation.
- Added a method to fetch unique trackable accounts.
- Enhanced collection fetching with pagination and account filtering.
___
<tr>
<td>
<details>
<summary><strong>WalletConnectButton.vue</strong><dd><code>Enhance wallet connection with multi-tenant support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> [PLA-2008] api 2.0

resources/js/components/TrackCollectionModal.vue
Bug fix
___
- Fixed an issue with track collection loading by adding a watcher on the `isOpen` prop to reset the `collectionId` and `loading` state when the modal is closed.
- Imported `watch` from Vue to implement the new functionality.
___
<tr>
<td>
<details>
<summary><strong>TrackCollectionModal.vue</strong><dd><code>Fix track collection loading by resetting state on close</code>&nbsp; </dd></summary>
<hr>
resources/js/components/TrackCollectionModal.vue
<li>Added <code>watch</code> from Vue to monitor <code>isOpen</code> prop.<br> <li> Reset <code>collectionId</code> and <code>loading</code> when modal is closed.<br>
</details>
</td>
<td><a …
=> [PLA-2042] fix track collection loading

resources/js/components/pages/Settings.vue, resources/js/components/pages/SettingsHelp.vue, resources/js/components/pages/SettingsWalletDaemon.vue
Enhancement
___
- Enhanced the settings page by adding a `v-model:help` binding to the `SettingsHelp` and `SettingsWalletDaemon` components, allowing for a more interactive help feature.
- Refactored the `SettingsHelp` component to simplify the UI logic and improve the transition animations for a smoother user experience.
- Introduced a help icon in the `SettingsWalletDaemon` component to toggle the help display, improving user guidance.
- Utilized `defineModel` for managing the `showHelp` state across components, ensuring consistent behavior.
___
<tr>
<td>
<details>
<summary><strong>Settings.vue</strong><dd><code>Enhance settings page with help toggle …
=> [PLA-2020] fix settings icon

resources/js/components/batch/forms/BatchTransferForm.vue, resources/js/components/slideovers/token/TransferTokenSlideover.vue
Bug fix
___
- Removed the `Keep Alive` option from the `BatchTransferForm` and `TransferTokenSlideover` components.
- Deleted all references to `keepAlive` in the form data and validation schemas.
- Simplified the form structure by removing unnecessary fields.
___
<tr>
<td>
<details>
<summary><strong>BatchTransferForm.vue</strong><dd><code>Remove Keep Alive option from BatchTransferForm</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/batch/forms/BatchTransferForm.vue
<li>Removed <code>Keep Alive</code> checkbox from the form.<br> <li> Deleted <code>simpleKeepAlive</code> and …
=> [PLA-2049] remove keepalive from transfer forms

resources/js/components/pages/create/CreateCollection.vue
Bug fix
___
- Fixed the logic for creating the `mintPolicy` object in the `createCollection` function by removing unnecessary conditions.
- Ensured that `mintPolicy` is always an object, which simplifies the code and potentially fixes issues related to undefined policies.
___
<tr>
<td>
<details>
<summary><strong>CreateCollection.vue</strong><dd><code>Simplify mintPolicy logic in createCollection function</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/create/CreateCollection.vue
<li>Removed the <code>hasMintPolicy</code> computed property.<br> <li> Simplified the <code>mintPolicy</code> object creation logic.<br> <li> Ensured …
=> [PLA-2008] fix create collection

resources/js/graphql/mutation/token/InfuseToken.ts
Bug fix
___
- Renamed the GraphQL mutation `InfuseToken` to `Infuse` to fix a naming issue.
___
<tr>
<td>
<details>
<summary><strong>InfuseToken.ts</strong><dd><code>Rename mutation from `InfuseToken` to `Infuse`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/graphql/mutation/token/InfuseToken.ts
- Renamed the `InfuseToken` mutation to `Infuse`.
</details>
</td>
<td><a href="https://github.com/enjin/platform-ui/pull/174/files#diff-02a79f4915887135f94ec6c6934bb09512f19f796d56c2b49fe316b25f567d15">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> [PLA-2065] fix infuse token mutation

resources/js/components/slideovers/fueltank/FreezeFuelTankSlideover.vue
___
- Enhanced the Fuel Tank Slideover component to dynamically handle both freezing and unfreezing actions based on the current state of the fuel tank.
- Updated UI elements such as titles and button text to reflect the dynamic nature of the action.
- Improved user feedback by modifying snackbar messages to indicate whether the action was a freeze or unfreeze.
- Fixed initialization of the `isFrozen` state to correctly reflect the current state of the fuel tank.
___
<tr>
<td>
<details>
<summary><strong>FreezeFuelTankSlideover.vue</strong><dd><code>Dynamic freeze/unfreeze functionality for Fuel Tank Slideover</code></dd></summary> …
=> [PLA-2075] fix freeze fueltank modal

resources/js/api/beam.ts, resources/js/components/Chip.vue, resources/js/components/pages/create/CreateBeam.vue, resources/js/components/slideovers/beam/DetailsBeamSlideover.vue, resources/js/graphql/mutation/beam/CreateBeam.ts, resources/js/graphql/query/beam/GetBeam.ts, resources/js/graphql/query/beam/GetBeams.ts
enhancement
___
- Enhanced the `DetailsBeamSlideover.vue` component to display `claimLimit` and `claimsRemaining`.
- Updated the `GetBeam` GraphQL query to include `claimLimit`, `claimsRemaining`, and `claimConditions`.
- Updated the `GetBeams` GraphQL query to include `claimLimit`, `claimsRemaining`, and `claimConditions`.
___
<tr>
<td>
<details>
<summary><strong>DetailsBeamSlideover.vue</strong><dd><code>Add claim limit and remaining claims display</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/slideovers/beam/DetailsBeamSlideover.vue
<li>Added display for …
=> [PLA-2072] fix beam details

resources/js/api/index.ts, resources/js/api/queries.ts, resources/js/components/App.vue, resources/js/components/DynamicBanner.vue, resources/js/graphql/query/GetBanners.ts
enhancement
___
- Introduced a new `DynamicBanner` component to display dynamic messages at the top of the application.
- Integrated the `DynamicBanner` into the main application layout in `App.vue`.
- Implemented logic for displaying, linking, and dismissing the banner, with state management using Vue's `ref` and `computed`.
- Added CSS transitions for smooth banner appearance and dismissal.
___
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Integrate DynamicBanner component into main application layout</code></dd></summary>
<hr>
<li>Added <code>DynamicBanner</code> component to the main template.<br> <li> …
=> [PLA-1973] add dynamic banner

resources/js/components/DynamicBanner.vue
bug_fix
___
- Fixed the logic for determining banner visibility by checking local storage for the banner key.
- Ensured that the banner is not shown if the key is set to 'true' in local storage.
___
<tr>
<td>
<details>
<summary><strong>DynamicBanner.vue</strong><dd><code>Fix banner visibility logic using local storage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/DynamicBanner.vue
<li>Modified the <code>enabled</code> computed property logic.<br> <li> Changed condition to check local storage for banner key.<br>
</details>
</td>
<td><a …
=> [PLA-1973] fix banner

resources/js/components/batch/forms/BatchMintForm.vue
Bug fix
___
- Removed the `required` attribute from the `imageUrl` field in the batch mint form.
- Ensures the image URL is no longer mandatory during batch minting.
___
<tr>
<td>
<details>
<summary><strong>BatchMintForm.vue</strong><dd><code>Made image URL optional in batch mint form</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/batch/forms/BatchMintForm.vue
<li>Removed the <code>required</code> attribute from the <code>imageUrl</code> field.<br> <li> Adjusted the batch mint form to make the image URL optional.
</details>
</td>
<td><a …
=> [PLA-3113] remove required image from batch mint

resources/js/api/collection.ts, resources/js/components/pages/Collections.vue, resources/js/graphql/query/GetCollections.ts
___
- Fixed incorrect query in `getCollection` method to use `getCollections` with IDs.
- Enhanced `getCollections` API to support collection IDs as input.
- Updated GraphQL query to include `collectionIds` parameter.
- Improved pagination logic in `loadMoreCollectionsWithObserver` method.
___
<tr>
<td>
<details>
<summary><strong>Collections.vue</strong><dd><code>Fix and enhance collection handling logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
resources/js/components/pages/Collections.vue
<li>Updated <code>getCollection</code> to use …
=> [PLA-2141] fix collection query
